import { describe, expect, it, vi } from 'vitest';
import { escapeCSV, formatCurrency, formatReadableDate, formatReadableDateTime, formatNumber, generateFilename, generateReportHeader, generateSectionHeader, keyValueToCSV, objectsToCSV, downloadCSV } from './exportUtils';

describe('exportUtils', () => {
  it('escapeCSV escapes quotes and commas', () => {
    expect(escapeCSV('a,b')).toBe('"a,b"');
    expect(escapeCSV('a"b')).toBe('"a""b"');
    expect(escapeCSV('plain')).toBe('plain');
    expect(escapeCSV('a\n')).toBe('"a\n"');
  });

  it('formatCurrency formats ETB with 2 decimals', () => {
    expect(formatCurrency(10)).toMatch(/^ETB\s+10\.00$/);
    expect(formatCurrency(Number.NaN)).toBe('ETB 0.00');
    expect(formatCurrency(undefined, 'USD')).toMatch(/^USD\s+0\.00$/);
  });

  it('formatReadableDate returns input for invalid dates', () => {
    expect(formatReadableDate('not-a-date')).toBe('not-a-date');
    expect(formatReadableDate(null)).toBe('');
  });

  it('formatReadableDateTime and formatNumber handle invalid inputs', () => {
    expect(formatReadableDateTime('not-a-date')).toBe('not-a-date');
    expect(formatReadableDateTime(undefined)).toBe('');
    expect(formatNumber(Number.NaN)).toBe('0');
    expect(formatNumber(12.3456, 1)).toBe('12.3');
  });

  it('formatReadableDate and formatReadableDateTime return original string when Date throws', () => {
    const RealDate = Date;

    (globalThis as any).Date = class extends RealDate {
      constructor(...args: any[]) {
        if (args[0] === 'boom') throw new Error('boom');
        if (!args.length) {
          super();
          return;
        }
        super(args[0] as any);
      }
    } as any;

    expect(formatReadableDate('boom')).toBe('boom');
    expect(formatReadableDateTime('boom')).toBe('boom');

    (globalThis as any).Date = RealDate;
  });

  it('generateFilename makes safe branch names', () => {
    expect(generateFilename('sales', 'Main Branch', '2026-02-10', '2026-02-11')).toBe('sales_main_branch_2026-02-10_to_2026-02-11');
    expect(generateFilename('sales', undefined, undefined, undefined)).toBe('sales_all');
  });

  it('objectsToCSV produces header and rows', () => {
    const rows = objectsToCSV(
      [{ a: 1, b: 'x' }, { a: 2, b: 'y' }],
      [
        { key: 'a', label: 'A' },
        { key: 'b', label: 'B' },
      ],
    );

    expect(rows[0]).toBe('A,B');
    expect(rows[1]).toBe('1,x');
    expect(rows[2]).toBe('2,y');
  });

  it('objectsToCSV escapes values with commas/quotes', () => {
    const rows = objectsToCSV(
      [{ a: 'x,y', b: 'a"b' }],
      [
        { key: 'a', label: 'A' },
        { key: 'b', label: 'B' },
      ],
    );

    expect(rows[0]).toBe('A,B');
    expect(rows[1]).toBe('"x,y","a""b"');
  });

  it('generateReportHeader and generateSectionHeader return stable formatting', () => {
    const lines = generateReportHeader({
      businessName: 'Biz',
      branchName: 'Main',
      reportTitle: 'Sales',
      fromDate: '2026-02-01T00:00:00.000Z',
      toDate: '2026-02-02T00:00:00.000Z',
      generatedBy: 'Alice',
    });

    expect(lines.join('\n')).toMatch(/Biz - Main/);
    expect(lines.join('\n')).toMatch(/SALES/);
    expect(lines.join('\n')).toMatch(/Report Period:/);
    expect(lines.join('\n')).toMatch(/Generated By: Alice/);

    const sec = generateSectionHeader('Totals');
    expect(sec[1]).toBe('--- TOTALS ---');

    const lines2 = generateReportHeader({
      businessName: 'Biz',
      reportTitle: 'Summary',
      fromDate: '2026-02-01T00:00:00.000Z',
      toDate: '2026-02-02T00:00:00.000Z',
    });
    expect(lines2.join('\n')).toMatch(/Biz\nSUMMARY/);
  });

  it('keyValueToCSV produces key,value rows with escaping', () => {
    const lines = keyValueToCSV([
      { label: 'A', value: 1 },
      { label: 'B', value: 'x,y' },
    ]);
    expect(lines[0]).toBe('A,1');
    expect(lines[1]).toBe('B,"x,y"');
  });

  it('downloadCSV triggers anchor download with BOM', () => {
    const createObjectURL = vi.fn(() => 'blob:mock');
    const revokeObjectURL = vi.fn();
    const click = vi.fn();

    (globalThis as any).URL.createObjectURL = createObjectURL;
    (globalThis as any).URL.revokeObjectURL = revokeObjectURL;

    const a = document.createElement('a');
    a.click = click;

    const originalCreateElement = document.createElement.bind(document);
    const createElementSpy = vi.spyOn(document, 'createElement').mockImplementation((tagName: any) => {
      if (tagName === 'a') return a;
      return originalCreateElement(tagName);
    });

    downloadCSV('a,b', 'report');

    expect(createObjectURL).toHaveBeenCalledTimes(1);
    expect(a.download).toBe('report.csv');
    expect(a.href).toBe('blob:mock');
    expect(click).toHaveBeenCalledTimes(1);
    expect(revokeObjectURL).toHaveBeenCalledWith('blob:mock');

    createElementSpy.mockRestore();
  });

  it('downloadCSV preserves filename when already .csv', () => {
    const createObjectURL = vi.fn(() => 'blob:mock');
    const revokeObjectURL = vi.fn();
    const click = vi.fn();

    (globalThis as any).URL.createObjectURL = createObjectURL;
    (globalThis as any).URL.revokeObjectURL = revokeObjectURL;

    const a = document.createElement('a');
    a.click = click;
    const originalCreateElement = document.createElement.bind(document);
    const createElementSpy = vi.spyOn(document, 'createElement').mockImplementation((tagName: any) => {
      if (tagName === 'a') return a;
      return originalCreateElement(tagName);
    });

    downloadCSV('a,b', 'report.csv');
    expect(a.download).toBe('report.csv');

    createElementSpy.mockRestore();
  });
});
