/**
 * Professional CSV Export Utilities for MirachPOS
 * Provides consistent, Excel-compatible report exports
 */

// UTF-8 BOM for Excel compatibility
export const UTF8_BOM = '\uFEFF';

/**
 * Escape a value for CSV format
 */
export const escapeCSV = (value: unknown): string => {
    const str = String(value ?? '');
    if (/[",\n\r]/.test(str)) {
        return `"${str.replace(/"/g, '""')}"`;
    }
    return str;
};

/**
 * Format currency with ETB prefix
 */
export const formatCurrency = (amount: number | null | undefined): string => {
    const num = Number(amount ?? 0);
    if (!Number.isFinite(num)) return 'ETB 0.00';
    return `ETB ${num.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
};

/**
 * Format a number with thousand separators
 */
export const formatNumber = (value: number | null | undefined, decimals = 2): string => {
    const num = Number(value ?? 0);
    if (!Number.isFinite(num)) return '0';
    return num.toLocaleString(undefined, { minimumFractionDigits: decimals, maximumFractionDigits: decimals });
};

/**
 * Format ISO date string to readable format (e.g., "Jan 10, 2026")
 */
export const formatReadableDate = (isoString: string | null | undefined): string => {
    if (!isoString) return '';
    try {
        const date = new Date(isoString);
        if (Number.isNaN(date.getTime())) return String(isoString);
        return date.toLocaleDateString(undefined, { month: 'short', day: '2-digit', year: 'numeric' });
    } catch {
        return String(isoString);
    }
};

/**
 * Format ISO datetime to readable format (e.g., "Jan 10, 2026 at 10:04 AM")
 */
export const formatReadableDateTime = (isoString: string | null | undefined): string => {
    if (!isoString) return '';
    try {
        const date = new Date(isoString);
        if (Number.isNaN(date.getTime())) return String(isoString);
        return date.toLocaleString(undefined, {
            month: 'short',
            day: '2-digit',
            year: 'numeric',
            hour: 'numeric',
            minute: '2-digit',
        });
    } catch {
        return String(isoString);
    }
};

/**
 * Generate professional report header for CSV exports
 */
export const generateReportHeader = (options: {
    businessName: string;
    branchName?: string;
    reportTitle: string;
    fromDate: string;
    toDate: string;
    generatedBy?: string;
}): string[] => {
    const lines: string[] = [];
    const separator = '='.repeat(50);

    lines.push(separator);
    lines.push(options.branchName
        ? `${options.businessName} - ${options.branchName}`
        : options.businessName);
    lines.push(options.reportTitle.toUpperCase());
    lines.push(separator);
    lines.push('');
    lines.push(`Report Period: ${formatReadableDate(options.fromDate)} - ${formatReadableDate(options.toDate)}`);
    lines.push(`Generated: ${formatReadableDateTime(new Date().toISOString())}`);
    if (options.generatedBy) {
        lines.push(`Generated By: ${options.generatedBy}`);
    }
    lines.push('');
    lines.push(separator);
    lines.push('');

    return lines;
};

/**
 * Generate a section header for CSV
 */
export const generateSectionHeader = (title: string): string[] => {
    return ['', `--- ${title.toUpperCase()} ---`, ''];
};

/**
 * Convert array of objects to CSV rows with proper headers
 */
export const objectsToCSV = <T extends Record<string, unknown>>(
    data: T[],
    columns: { key: keyof T; label: string }[]
): string[] => {
    const lines: string[] = [];

    // Header row
    lines.push(columns.map((col) => escapeCSV(col.label)).join(','));

    // Data rows
    for (const row of data) {
        lines.push(columns.map((col) => escapeCSV(row[col.key])).join(','));
    }

    return lines;
};

/**
 * Download CSV content as file
 */
export const downloadCSV = (content: string, filename: string): void => {
    const csvContent = UTF8_BOM + content;
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename.endsWith('.csv') ? filename : `${filename}.csv`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
};

/**
 * Create a simple key-value table for CSV
 */
export const keyValueToCSV = (data: Array<{ label: string; value: string | number }>): string[] => {
    return data.map((row) => [escapeCSV(row.label), escapeCSV(row.value)].join(','));
};

export type ExportFormat = 'csv' | 'excel' | 'pdf';

/**
 * Generate safe filename from report parameters
 */
export const generateFilename = (
    reportType: string,
    branchName?: string,
    fromDate?: string,
    toDate?: string
): string => {
    const safeBranch = (branchName || 'all').replace(/[^a-zA-Z0-9]/g, '_').toLowerCase();
    const dateFrom = fromDate ? fromDate.slice(0, 10) : '';
    const dateTo = toDate ? toDate.slice(0, 10) : '';
    const datePart = dateFrom && dateTo ? `_${dateFrom}_to_${dateTo}` : '';
    return `${reportType}_${safeBranch}${datePart}`;
};
